"""Physics DEGADIS does not have.

Everything in :mod:`degali.core` is a port of DEGADIS 2.1 and is validated
against it. This package is different: it implements published theory the
original lacks, so nothing here can be checked against the Fortran and it is
kept separate for that reason.

:mod:`~degali.addons.liftoff`
    Buoyant lift-off of a ground-based plume, from the URAHFREP integral
    model, as a standalone plume.

:mod:`~degali.addons.unified`
    Dense slumping and buoyant rise in one set of equations, with no handover
    threshold between them: entrainment blends between the ground-layer law
    and the free-perimeter law by how much of the cross-section is still on
    the ground. This removes the one free parameter the staged approach needed.

:mod:`~degali.addons.buoyant`
    The same vertical momentum balance as a *closure* for the downwind model,
    so an existing DEGADIS run can be given the ability to lift its cloud off
    the ground by swapping one object. Dense behaviour is unchanged; the
    difference appears only where DEGADIS would have frozen the cloud in
    place.
"""

from .unified import UnifiedClosure
from .axisymmetric_jet import (
    AxisymmetricJetResult,
    AxisymmetricJetSource,
    ConservedGaussianJet,
    InitialEntrainmentResult,
    SourceEnthalpyBoundary,
    entrain_and_heat_initial_plug,
)
from .hydrogen_eos import HydrogenGasDeparture, hydrogen_gas_departure
from .energy_crosswind import (
    IndependentEnergyCrosswind,
    IndependentEnergyJetResult,
    IndependentEnergyProjection,
)
from .yawed_crosswind import YawedCrosswind, YawedTrajectory
from .wall_jet_transition import (
    FiniteWallJetCrosswind,
    FiniteWallJetResult,
    WallJetDiagnostics,
    WallJetTransitionConfig,
)
from .transient_receptor import (
    FixedReceptor,
    ReceptorTrace,
    SourceHistory,
    SourcePacket,
    SteadyPlumeTable,
    WindowStatistics,
    WindHistory,
    first_order_sensor_response,
    meteorological_from_to_math_radians,
    replay_fixed_receptors,
    replay_fixed_receptors_with_source_history,
)
from .source_state_ledger import (
    SOURCE_STATE_LEDGER_SCHEMA,
    SourceState,
    SourceStateLedger,
)
from .post_impact_walljet import (
    POST_IMPACT_WALLJET_SCHEMA,
    biased_radial_walljet_field,
    bifurcated_walljet_field,
    radial_walljet_field,
    radial_walljet_mixing,
    redistribute_vertical_profile,
    source_state_profile_weights,
)
from .transient_dense_gas_3d import (
    TRANSIENT_DENSE_GAS_3D_SCHEMA,
    DenseGas3DReceptor,
    TransientDenseGas3DConfig,
    TransientDenseGas3DResult,
    solve_transient_dense_gas_3d,
)
from .event_balanced_metrics import (
    EVENT_BALANCED_METRICS_SCHEMA,
    EventBalancedMetricScore,
    EventMetricObservation,
    EventMetricSummary,
    score_event_balanced_metrics,
)
from .time_history_execution import (
    TIME_HISTORY_EXECUTION_GATE_CODES,
    TIME_HISTORY_EXECUTION_SCHEMA,
    TimeHistoryExecutionGate,
    TimeHistoryExecutionResult,
    run_manifest_bound_time_history,
)
from .time_history_io import (
    TIME_HISTORY_CSV_INPUT_SCHEMA,
    ImportedSourceHistory,
    ImportedWindHistory,
    SourceHistoryCsvMap,
    WindHistoryCsvMap,
    read_source_history_csv,
    read_wind_history_csv,
)
from .site_geometry import (
    AxisAlignedCuboid,
    OrientedCuboid,
    ObstacleEncounter,
    ObstacleScreenResult,
    SegmentIntersection,
    TransverseWall,
    WindFrame,
    screen_trajectory,
)
from .obstacle_wake_validation import (
    DenseGasFenceBenchmark,
    DenseGasFenceObservation,
    NeutralObstacleWakeBenchmark,
    NeutralObstacleWakePoint,
    pair_smedis_fence_trials,
    read_aij_case_h,
    read_smedis_fence_pair,
)
from .transport_evidence import (
    PARTICLE_SLIP_BOUNDARY,
    TURBULENCE_BOUNDARY,
    TransportEvidenceBoundary,
)
from .notional import (
    EnergyConservingNotionalNozzle,
    IsentropicThroat,
    MeasuredThroatExpansion,
    NotionalNozzle,
    choking_pressure,
    energy_conserving_notional_nozzle,
    expand_measured_throat_to_ambient,
    isentropic_throat,
    notional_nozzle,
)
from .cryogenic_blowdown import (
    CryogenicBlowdownConfig,
    CryogenicBlowdownResult,
    CryogenicBlowdownState,
    TransientPipeWall,
    TransientTankWall,
    blowdown_state_to_flashing_droplet_source,
    blowdown_state_to_homogeneous_evaporation_source,
    blowdown_state_to_lh2_source,
    hem_blowdown_state_to_flashing_droplet_source,
    hem_blowdown_state_to_homogeneous_evaporation_source,
    run_cryogenic_blowdown,
)
from .pool_evaporation import (
    PoolEvaporationResult,
    PoolEvaporationStep,
    SolidSubstrate,
    semi_infinite_heat_flux,
    substrate_conduction_evaporation,
)
from .dynamic_pool import (
    ConstantHeatFluxSurface,
    DynamicPoolNumerics,
    DynamicPoolResult,
    DynamicPoolStep,
    simulate_axisymmetric_spreading_pool,
)
from .droplet_rainout import (
    DropletClass,
    DropletClassOutcome,
    DropletEvaporationSegment,
    DropletPopulationResult,
    DropletTransportInput,
    RainoutPoolCouplingResult,
    concurrent_rainout_pool,
    dynamic_rainout_pool,
    droplet_transport_input_from_flash,
    post_release_rainout_pool,
    transport_droplet_population,
)
from .finite_release import (
    FiniteReleasePuffHandoff,
    SteadyWindApplicability,
    assess_steady_wind_applicability,
    finite_release_puff_handoff,
)
from .finite_puff import (
    GaussianPuffConfig,
    GaussianPuffResult,
    GaussianPuffState,
    PuffReceptorTrace,
    integrate_finite_gaussian_puff,
)
from .lh2_droplets import (
    critical_droplet_diameter_for_phase_delay,
    critical_diffusivity_for_phase_delay,
    FlashingHydrogenDropletSource,
    direct_vapour_jet_source_from_flash,
    gasflow_phase_relaxation_coefficient,
    HomogeneousEquilibriumHydrogenSource,
    flashing_hydrogen_droplet_source,
    homogeneous_equilibrium_hydrogen_source,
    homogeneous_equilibrium_hydrogen_source_from_postflash,
    minimum_heat_limited_hydrogen_evaporation_time,
)
from .cryogenic_air import (
    AirPhaseEquilibrium,
    N2O2CondensedPhaseScope,
    CondensedAirSource,
    CondensedAirStep,
    HydrogenEvaporationEndpoint,
    MultiphaseHydrogenSourcePlane,
    TwoVelocityRelaxation,
    TwoVelocityPhaseStep,
    LiZone3,
    air_saturation_pressure,
    cunningham_corrected_particle_relaxation_time,
    davies_cunningham_slip_correction,
    equilibrium_air_phase_split,
    n2o2_condensed_phase_scope,
    li2026_zone3,
    multiphase_hydrogen_evaporation_endpoint,
    multiphase_hydrogen_source_plane,
    minimum_heat_limited_sublimation_time,
    particle_relaxation_time,
    particle_terminal_velocity,
    particle_knudsen_number,
    schiller_naumann_relaxation_time,
    relax_two_velocity_drag,
    relax_two_velocity_schiller_naumann_drag,
    advance_two_velocity_phase_step,
    ranz_marshall_transfer_number,
    transported_condensed_air_source,
)
from .buoyant import LAMBDA, BuoyantClosure, make_buoyant
from .liftoff import (
    ALPHA,
    BETA,
    GAMMA,
    RI_CLEAR,
    RI_ONSET,
    RI_SUBSTANTIAL,
    LiftoffPlume,
    LiftoffResult,
    LiftoffState,
    liftoff_regime,
    richardson_liftoff,
)
from .field_contracts import (
    BoundedValue,
    CircularBoundedValue,
    FieldCoordinateReference,
    FieldValidationEvidence,
    FieldApplicability,
    FieldScenario,
    PressureDrivenMassFlowBoundary,
    ReleaseSource,
    SensorModel,
    SurfaceBoundary,
    WeatherState,
    assess_field_applicability,
    bounded,
)
from .field_meteorology import (
    FieldStabilityAlternatives,
    FieldWindHistory,
    StabilityScalarMixingClosure,
)
from .field_distributed_source import FieldDistributedVapourSource
from .field_validation import (
    FIELD_VALIDATION_GATE_CODES,
    FIELD_VALIDATION_SCORE_SCHEMA,
    FieldValidationDataset,
    FieldValidationObservation,
    FieldValidationScore,
    field_validation_dataset_from_csv,
    field_validation_score_record,
    score_field_model_against_validation,
)
from .field_validation_io import (
    FIELD_VALIDATION_INPUT_SCHEMA,
    FieldValidationManifestReference,
    FieldValidationCase,
    field_validation_case_from_mapping,
    field_validation_case_record,
    read_field_validation_case_json,
    write_field_validation_case_json,
)
from .field_evidence_audit import (
    FIELD_EVIDENCE_AUDIT_GATE_CODES,
    FIELD_EVIDENCE_AUDIT_SCHEMA,
    FIELD_EVIDENCE_AUDIT_EXECUTION_SCHEMA,
    FieldEvidenceCandidate,
    FieldEvidenceAudit,
    audit_field_evidence,
    field_evidence_audit_from_mapping,
    field_evidence_audit_record,
    read_field_evidence_audit_json,
    write_field_evidence_audit_json,
)
from .field_evidence_manifest import (
    FIELD_EVIDENCE_MANIFEST_SCHEMA,
    FIELD_EVIDENCE_MANIFEST_EXECUTION_SCHEMA,
    FIELD_EVIDENCE_MANIFEST_GATE_CODES,
    SENSOR_CALIBRATION_STATUSES,
    FieldEvidenceManifestArtifact,
    FieldEvidenceManifest,
    field_evidence_manifest_record,
    field_evidence_manifest_from_mapping,
    read_field_evidence_manifest_json,
    write_field_evidence_manifest_json,
)
from .field_source_io import (
    FIELD_SOURCE_SCHEDULE_INPUT_SCHEMA,
    FIELD_SOURCE_SCHEDULE_EXECUTION_SCHEMA,
    FieldSourceScheduleEvidence,
    FieldAtmosphericSourceSchedule,
    field_source_schedule_from_csv,
    field_source_schedule_case_from_mapping,
    read_field_source_schedule_json,
    field_source_schedule_record,
    write_field_source_schedule_json,
)
from .field_droplet_launch import (
    DropletVapourLaunchBoundary,
    FieldDropletHandoffRefinementCase,
    FieldDropletHandoffRefinementStudy,
    distributed_sources_from_droplet_evaporation,
    run_field_droplet_handoff_refinement_study,
)
from .field_jet import (
    FieldJetScalarHandoff,
    field_jet_scalar_handoff_from_near_field,
    jet_scalar_handoff_location,
    request_with_jet_scalar_handoff,
)
from .semi_fv_obstacle import (
    DistributedScalarSource,
    RectangularObstacle2D,
    SemiFVConfig,
    SemiFVDiagnostics,
    SemiFVReceptor,
    SemiFVReceptorRefinement,
    SemiFVReceptorTrace,
    SemiFVRefinementStudy,
    SemiFVResult,
    SourceRateSchedule,
    run_semi_fv_refinement_study,
    solve_semi_fv_obstacle,
)
from .field_lh2 import (
    FieldBlowdownVapourSchedule,
    FieldLH2FlashResult,
    FieldLH2SourcePreparation,
    build_lh2_saturation_table_for_temperature_bounds,
    build_lh2_saturation_table_for_release,
    direct_vapour_schedule_from_cryogenic_blowdown,
    lh2_flash_source_from_release,
    pressure_driven_lh2_mass_flow,
    prepare_field_lh2_flash,
    release_with_pressure_driven_lh2_mass_flow,
)
from .lh2_property_table import LH2SaturationTable
from .field_geometry import (
    FieldObstacleGeometryUncertainty,
    WindPlaneObstacleProjection,
    project_cuboid_to_wind_plane,
)
from .field_observation import (
    DRY_AIR_MOLAR_MASS_KG_MOL,
    HYDROGEN_MOLAR_MASS_KG_MOL,
    FieldSensorTrace,
    apply_sensor_model,
    h2_mole_fraction_from_mass_concentration,
    trailing_time_average,
)
from .field_workflow import (
    FieldSensorDeployment,
    FieldSensorDeploymentResult,
    FieldSensorArrayUncertaintyCase,
    FieldSensorArrayUncertaintyEnvelope,
    FieldSemiFVEnvelope,
    FieldSemiFVEnvelopeCase,
    FieldSemiFVRefinementResult,
    FieldSemiFVRequest,
    FieldSemiFVScreeningResult,
    run_field_semi_fv_envelope,
    run_field_sensor_array_uncertainty_envelope,
    run_field_semi_fv_refinement_study,
    run_field_semi_fv_screening,
)
from .field_superposition import (
    FieldSensorBranch,
    FieldSensorSuperposition,
    superpose_field_sensor_branches,
)
from .field_comparison import (
    FIELD_MODEL_COMPARISON_GATE_CODES,
    FIELD_MODEL_COMPARISON_REPORT_SCHEMA,
    FieldComparisonBasis,
    FieldComparisonEvidence,
    FieldModelExecutionProvenance,
    FieldModelComparison,
    FieldModelDecisionImpact,
    FieldModelComparisonRow,
    FieldModelSensorSet,
    FieldSensorCsvProvenance,
    FieldSensorPrediction,
    compare_field_model_sensor_sets,
    field_model_decision_impact,
    field_model_decision_impact_record,
    field_model_comparison_report,
    field_model_sensor_set_from_csv,
    write_field_model_sensor_set_csv,
    field_model_sensor_set_from_screening,
    field_model_sensor_set_from_superposition,
)
from .field_comparison_io import (
    FIELD_MODEL_COMPARISON_INPUT_SCHEMA,
    FieldModelComparisonCase,
    field_model_comparison_case_from_mapping,
    field_model_comparison_case_record,
    read_field_model_comparison_case_json,
    write_field_model_comparison_case_json,
)
from .field_execution import (
    FIELD_EXECUTION_VERIFICATION_SCHEMA,
    verify_field_execution_artifact,
)
from .field_phase_routing import (
    FieldPhaseRoutingConfig,
    FieldPhaseRoutingEnvelope,
    FieldPhaseRoutingEnvelopeCase,
    FieldPhaseRoutingResult,
    FieldPhaseRoutingUncertainty,
    run_field_phase_routing,
    run_field_phase_routing_envelope,
)
from .field_phase_transport import (
    FIELD_PHASE_ROUTING_TRANSPORT_ENVELOPE_SCHEMA,
    FieldPhaseRoutingTransportEnvelope,
    FieldPhaseRoutingTransportEnvelopeCase,
    field_phase_routing_transport_envelope_report,
    run_field_phase_routing_transport_envelope,
)
from .field_operational_phase_transport import (
    FIELD_OPERATIONAL_PHASE_ROUTING_TRANSPORT_ENVELOPE_SCHEMA,
    FieldOperationalPhaseRoutingTransportEnvelope,
    FieldOperationalPhaseRoutingTransportEnvelopeCase,
    field_operational_phase_routing_transport_envelope_report,
    run_field_operational_phase_routing_transport_envelope,
)
from .field_report import (
    FIELD_DROPLET_HANDOFF_REFINEMENT_REPORT_SCHEMA,
    FIELD_JOINT_MEASURED_HISTORY_ENVELOPE_REPORT_SCHEMA,
    FIELD_MEASURED_HISTORY_ENVELOPE_REPORT_SCHEMA,
    FIELD_SEMI_FV_ENVELOPE_REPORT_SCHEMA,
    FIELD_SENSOR_ARRAY_UNCERTAINTY_ENVELOPE_REPORT_SCHEMA,
    FIELD_SCREENING_REPORT_SCHEMA,
    FIELD_SENSOR_SUPERPOSITION_REPORT_SCHEMA,
    field_refinement_report,
    field_droplet_handoff_refinement_report,
    field_joint_measured_history_envelope_report,
    field_measured_history_envelope_report,
    field_semi_fv_envelope_report,
    field_sensor_array_uncertainty_envelope_report,
    field_screening_report,
    field_sensor_superposition_report,
    write_field_refinement_report,
    write_field_screening_report,
)
from .field_batch import (
    FIELD_BATCH_MANIFEST_SCHEMA,
    FIELD_BATCH_SUMMARY_SCHEMA,
    FieldBatchCase,
    FieldBatchExport,
    field_batch_decision_summary,
    export_field_screening_batch,
)
from .field_batch_io import (
    FIELD_BATCH_INPUT_SCHEMA,
    FieldBatchExecutionOptions,
    FieldBatchInputCase,
    FieldBatchInput,
    field_batch_input_from_mapping,
    read_field_batch_input_json,
)
from .field_case_io import (
    FIELD_PHASE_ROUTING_SCREENING_INPUT_SCHEMA,
    FIELD_SCREENING_INPUT_SCHEMA,
    FieldPhaseRoutingTransportInput,
    FieldScreeningCase,
    field_screening_case_from_mapping,
    field_screening_request_from_mapping,
    read_field_screening_case_json,
    read_field_screening_request_json,
)
from .field_decision import (
    FIELD_OPERATIONAL_GATE_CODES,
    FIELD_OPERATIONAL_SCREENING_DECISION_SCHEMA,
    FieldConditionalReviewAuthorization,
    FieldOperationalScreeningDecision,
    evaluate_field_operational_screening,
    field_operational_screening_decision_record,
)
from .field_operational_envelope import (
    FIELD_OPERATIONAL_UNCERTAINTY_ENVELOPE_SCHEMA,
    FieldOperationalUncertaintyEnvelope,
    FieldOperationalUncertaintyEnvelopeCase,
    field_operational_uncertainty_envelope_report,
    run_field_operational_uncertainty_envelope,
)
from .field_operational_history import (
    FIELD_OPERATIONAL_MEASURED_HISTORY_ENVELOPE_SCHEMA,
    FieldOperationalMeasuredHistoryEnvelope,
    FieldOperationalMeasuredHistoryEnvelopeCase,
    field_operational_joint_measured_history_envelope_report,
    run_field_operational_joint_measured_history_envelope,
    run_field_operational_joint_pressure_driven_history_envelope,
)
from .field_operational_sensor_array import (
    FIELD_OPERATIONAL_SENSOR_ARRAY_ENVELOPE_SCHEMA,
    FieldOperationalSensorArrayEnvelope,
    FieldOperationalSensorArrayEnvelopeCase,
    field_operational_sensor_array_envelope_report,
    run_field_operational_sensor_array_envelope,
)
from .field_operational_source_sensor import (
    FIELD_OPERATIONAL_SOURCE_SENSOR_ENVELOPE_SCHEMA,
    FieldOperationalSourceSensorEnvelope,
    FieldOperationalSourceSensorEnvelopeCase,
    field_operational_source_sensor_envelope_report,
    run_field_operational_source_sensor_envelope,
)
from .field_history import (
    FieldJointMeasuredHistoryScreeningCase,
    FieldJointMeasuredHistoryScreeningEnvelope,
    FieldMeasuredFlashEnvelope,
    FieldMeasuredFlashEnvelopeCase,
    FieldMeasuredFlashSchedule,
    FieldMeasuredHistoryScreeningCase,
    FieldMeasuredHistoryScreeningEnvelope,
    MeasuredHistoryQualityAssessment,
    MeasuredHistoryQualityCriteria,
    MeasuredReleaseHistory,
    MeasuredTimeSeries,
    PressureDrivenMeasuredHistory,
    assess_measured_history_quality,
    direct_vapour_schedule_envelope_from_measured_history,
    direct_vapour_schedule_from_measured_history,
    direct_vapour_schedule_envelope_from_pressure_driven_history,
    direct_vapour_schedule_from_pressure_driven_history,
    request_with_measured_flash_schedule,
    request_with_pressure_driven_history_schedule,
    run_field_joint_measured_history_envelope,
    run_field_joint_pressure_driven_history_envelope,
    run_field_measured_history_envelope,
    run_field_pressure_driven_history_envelope,
)
from .field_historian_io import (
    HistorianCsvChannel,
    ImportedMeasuredReleaseHistory,
    ImportedPressureDrivenMeasuredHistory,
    MeasuredHistoryCsvMap,
    MeasuredHistoryCsvProvenance,
    PressureDrivenHistoryCsvMap,
    direct_vapour_schedule_from_imported_history,
    direct_vapour_schedule_from_imported_pressure_driven_history,
    read_measured_history_csv,
    read_pressure_driven_history_csv,
)
from .field_pool_launch import (
    FieldPoolVapourSchedule,
    PoolVapourLaunchBoundary,
    distributed_source_from_pool_vapour_schedule,
    pool_vapour_schedule_from_phase_routing,
    request_with_pool_vapour_schedule,
)

__all__ = [
    "UnifiedClosure",
    "AxisymmetricJetSource", "AxisymmetricJetResult", "ConservedGaussianJet",
    "InitialEntrainmentResult", "entrain_and_heat_initial_plug",
    "IndependentEnergyCrosswind", "IndependentEnergyProjection",
    "IndependentEnergyJetResult",
    "YawedCrosswind", "YawedTrajectory",
    "FiniteWallJetCrosswind", "FiniteWallJetResult",
    "WallJetDiagnostics", "WallJetTransitionConfig",
    "FixedReceptor", "ReceptorTrace", "SourceHistory", "SourcePacket", "SteadyPlumeTable",
    "WindowStatistics", "WindHistory", "first_order_sensor_response",
    "meteorological_from_to_math_radians", "replay_fixed_receptors",
    "replay_fixed_receptors_with_source_history",
    "SOURCE_STATE_LEDGER_SCHEMA", "SourceState", "SourceStateLedger",
    "POST_IMPACT_WALLJET_SCHEMA", "radial_walljet_field",
    "biased_radial_walljet_field", "bifurcated_walljet_field",
    "radial_walljet_mixing", "source_state_profile_weights",
    "redistribute_vertical_profile",
    "TRANSIENT_DENSE_GAS_3D_SCHEMA", "DenseGas3DReceptor",
    "TransientDenseGas3DConfig", "TransientDenseGas3DResult",
    "solve_transient_dense_gas_3d",
    "EVENT_BALANCED_METRICS_SCHEMA", "EventMetricObservation", "EventMetricSummary",
    "EventBalancedMetricScore", "score_event_balanced_metrics",
    "TIME_HISTORY_EXECUTION_SCHEMA", "TIME_HISTORY_EXECUTION_GATE_CODES",
    "TimeHistoryExecutionGate", "TimeHistoryExecutionResult",
    "run_manifest_bound_time_history",
    "TIME_HISTORY_CSV_INPUT_SCHEMA", "SourceHistoryCsvMap", "WindHistoryCsvMap",
    "ImportedSourceHistory", "ImportedWindHistory",
    "read_source_history_csv", "read_wind_history_csv",
    "WindFrame", "AxisAlignedCuboid", "OrientedCuboid", "TransverseWall",
    "SegmentIntersection", "ObstacleEncounter", "ObstacleScreenResult",
    "screen_trajectory",
    "DenseGasFenceBenchmark", "DenseGasFenceObservation",
    "NeutralObstacleWakeBenchmark", "NeutralObstacleWakePoint",
    "pair_smedis_fence_trials", "read_aij_case_h", "read_smedis_fence_pair",
    "TransportEvidenceBoundary", "TURBULENCE_BOUNDARY", "PARTICLE_SLIP_BOUNDARY",
    "SourceEnthalpyBoundary", "HydrogenGasDeparture", "hydrogen_gas_departure",
    "NotionalNozzle", "notional_nozzle", "choking_pressure",
    "IsentropicThroat", "isentropic_throat",
    "EnergyConservingNotionalNozzle", "energy_conserving_notional_nozzle",
    "MeasuredThroatExpansion", "expand_measured_throat_to_ambient",
    "CryogenicBlowdownConfig", "CryogenicBlowdownState",
    "CryogenicBlowdownResult", "TransientTankWall", "TransientPipeWall",
    "blowdown_state_to_lh2_source",
    "blowdown_state_to_flashing_droplet_source",
    "blowdown_state_to_homogeneous_evaporation_source", "run_cryogenic_blowdown",
    "hem_blowdown_state_to_flashing_droplet_source",
    "hem_blowdown_state_to_homogeneous_evaporation_source",
    "SolidSubstrate", "PoolEvaporationStep", "PoolEvaporationResult",
    "semi_infinite_heat_flux", "substrate_conduction_evaporation",
    "ConstantHeatFluxSurface", "DynamicPoolNumerics", "DynamicPoolStep",
    "DynamicPoolResult",
    "simulate_axisymmetric_spreading_pool",
    "DropletClass", "DropletEvaporationSegment", "DropletClassOutcome", "DropletPopulationResult",
    "DropletTransportInput", "RainoutPoolCouplingResult",
    "transport_droplet_population", "concurrent_rainout_pool",
    "dynamic_rainout_pool",
    "droplet_transport_input_from_flash",
    "post_release_rainout_pool",
    "FiniteReleasePuffHandoff", "SteadyWindApplicability",
    "finite_release_puff_handoff", "assess_steady_wind_applicability",
    "GaussianPuffConfig", "GaussianPuffResult", "GaussianPuffState",
    "PuffReceptorTrace", "integrate_finite_gaussian_puff",
    "FlashingHydrogenDropletSource", "flashing_hydrogen_droplet_source",
    "direct_vapour_jet_source_from_flash",
    "gasflow_phase_relaxation_coefficient",
    "critical_droplet_diameter_for_phase_delay",
    "critical_diffusivity_for_phase_delay",
    "HomogeneousEquilibriumHydrogenSource",
    "homogeneous_equilibrium_hydrogen_source",
    "homogeneous_equilibrium_hydrogen_source_from_postflash",
    "minimum_heat_limited_hydrogen_evaporation_time",
    "AirPhaseEquilibrium", "N2O2CondensedPhaseScope",
    "equilibrium_air_phase_split", "n2o2_condensed_phase_scope",
    "CondensedAirSource", "CondensedAirStep", "transported_condensed_air_source",
    "HydrogenEvaporationEndpoint", "multiphase_hydrogen_evaporation_endpoint",
    "MultiphaseHydrogenSourcePlane", "multiphase_hydrogen_source_plane",
    "TwoVelocityRelaxation", "relax_two_velocity_drag",
    "relax_two_velocity_schiller_naumann_drag",
    "TwoVelocityPhaseStep", "advance_two_velocity_phase_step",
    "LiZone3", "li2026_zone3", "air_saturation_pressure",
    "particle_knudsen_number", "davies_cunningham_slip_correction",
    "cunningham_corrected_particle_relaxation_time",
    "particle_relaxation_time", "schiller_naumann_relaxation_time",
    "particle_terminal_velocity",
    "ranz_marshall_transfer_number",
    "minimum_heat_limited_sublimation_time",
    "BuoyantClosure", "make_buoyant", "LAMBDA",
    "LiftoffPlume", "LiftoffResult", "LiftoffState",
    "richardson_liftoff", "liftoff_regime",
    "ALPHA", "BETA", "GAMMA", "RI_ONSET", "RI_SUBSTANTIAL", "RI_CLEAR",
    "BoundedValue", "CircularBoundedValue", "FieldCoordinateReference", "FieldValidationEvidence", "bounded", "ReleaseSource", "WeatherState", "SensorModel",
    "SurfaceBoundary", "FieldScenario", "FieldApplicability", "PressureDrivenMassFlowBoundary",
    "assess_field_applicability", "RectangularObstacle2D", "SourceRateSchedule",
    "DistributedScalarSource", "SemiFVConfig",
    "FieldStabilityAlternatives", "StabilityScalarMixingClosure", "FieldWindHistory",
    "FieldDistributedVapourSource",
    "FIELD_VALIDATION_SCORE_SCHEMA", "FIELD_VALIDATION_GATE_CODES", "FieldValidationObservation",
    "FieldValidationDataset", "FieldValidationScore",
    "field_validation_dataset_from_csv", "score_field_model_against_validation",
    "field_validation_score_record",
    "FIELD_VALIDATION_INPUT_SCHEMA", "FieldValidationManifestReference",
    "FieldValidationCase",
    "field_validation_case_from_mapping", "field_validation_case_record",
    "read_field_validation_case_json", "write_field_validation_case_json",
    "FIELD_EVIDENCE_AUDIT_SCHEMA", "FIELD_EVIDENCE_AUDIT_EXECUTION_SCHEMA",
    "FIELD_EVIDENCE_AUDIT_GATE_CODES",
    "FieldEvidenceCandidate", "FieldEvidenceAudit", "audit_field_evidence",
    "field_evidence_audit_from_mapping", "field_evidence_audit_record",
    "read_field_evidence_audit_json", "write_field_evidence_audit_json",
    "FIELD_EVIDENCE_MANIFEST_SCHEMA", "FIELD_EVIDENCE_MANIFEST_EXECUTION_SCHEMA",
    "FIELD_EVIDENCE_MANIFEST_GATE_CODES", "FieldEvidenceManifestArtifact",
    "FieldEvidenceManifest", "field_evidence_manifest_record",
    "field_evidence_manifest_from_mapping", "read_field_evidence_manifest_json",
    "write_field_evidence_manifest_json",
    "FIELD_EXECUTION_VERIFICATION_SCHEMA", "verify_field_execution_artifact",
    "FIELD_SOURCE_SCHEDULE_INPUT_SCHEMA", "FIELD_SOURCE_SCHEDULE_EXECUTION_SCHEMA",
    "FieldSourceScheduleEvidence", "FieldAtmosphericSourceSchedule",
    "field_source_schedule_from_csv", "field_source_schedule_case_from_mapping",
    "read_field_source_schedule_json", "write_field_source_schedule_json",
    "field_source_schedule_record",
    "DropletVapourLaunchBoundary", "distributed_sources_from_droplet_evaporation",
    "FieldDropletHandoffRefinementCase", "FieldDropletHandoffRefinementStudy",
    "run_field_droplet_handoff_refinement_study",
    "FieldJetScalarHandoff", "field_jet_scalar_handoff_from_near_field",
    "jet_scalar_handoff_location", "request_with_jet_scalar_handoff",
    "FieldSensorBranch", "FieldSensorSuperposition", "superpose_field_sensor_branches",
    "SemiFVDiagnostics", "SemiFVReceptor", "SemiFVReceptorTrace",
    "SemiFVReceptorRefinement", "SemiFVRefinementStudy", "SemiFVResult",
    "solve_semi_fv_obstacle", "run_semi_fv_refinement_study",
    "FieldBlowdownVapourSchedule", "FieldLH2FlashResult", "FieldLH2SourcePreparation",
    "pressure_driven_lh2_mass_flow", "release_with_pressure_driven_lh2_mass_flow",
    "lh2_flash_source_from_release", "prepare_field_lh2_flash",
    "build_lh2_saturation_table_for_temperature_bounds",
    "build_lh2_saturation_table_for_release",
    "direct_vapour_schedule_from_cryogenic_blowdown", "LH2SaturationTable",
    "FieldObstacleGeometryUncertainty",
    "WindPlaneObstacleProjection", "project_cuboid_to_wind_plane",
    "DRY_AIR_MOLAR_MASS_KG_MOL", "HYDROGEN_MOLAR_MASS_KG_MOL",
    "FieldSensorTrace", "apply_sensor_model",
    "h2_mole_fraction_from_mass_concentration", "trailing_time_average",
    "FieldSemiFVRequest", "FieldSemiFVScreeningResult",
    "FieldSensorDeployment", "FieldSensorDeploymentResult",
    "FieldSensorArrayUncertaintyCase", "FieldSensorArrayUncertaintyEnvelope",
    "FieldSemiFVEnvelopeCase", "FieldSemiFVEnvelope", "FieldSemiFVRefinementResult",
    "run_field_semi_fv_screening", "run_field_semi_fv_envelope",
    "run_field_sensor_array_uncertainty_envelope",
    "run_field_semi_fv_refinement_study",
    "FieldComparisonBasis", "FieldComparisonEvidence", "FieldModelExecutionProvenance",
    "FieldSensorPrediction", "FieldSensorCsvProvenance",
    "FieldModelSensorSet", "field_model_sensor_set_from_csv",
    "write_field_model_sensor_set_csv",
    "field_model_sensor_set_from_screening",
    "field_model_sensor_set_from_superposition",
    "FieldModelComparisonRow", "FieldModelComparison",
    "FieldModelDecisionImpact",
    "compare_field_model_sensor_sets",
    "field_model_decision_impact", "field_model_decision_impact_record",
    "FIELD_MODEL_COMPARISON_GATE_CODES", "FIELD_MODEL_COMPARISON_REPORT_SCHEMA",
    "field_model_comparison_report",
    "FIELD_MODEL_COMPARISON_INPUT_SCHEMA", "FieldModelComparisonCase",
    "field_model_comparison_case_from_mapping", "field_model_comparison_case_record",
    "read_field_model_comparison_case_json", "write_field_model_comparison_case_json",
    "FieldPhaseRoutingConfig", "FieldPhaseRoutingResult", "FieldPhaseRoutingUncertainty",
    "FieldPhaseRoutingEnvelopeCase", "FieldPhaseRoutingEnvelope",
    "run_field_phase_routing", "run_field_phase_routing_envelope",
    "FIELD_PHASE_ROUTING_TRANSPORT_ENVELOPE_SCHEMA",
    "FieldPhaseRoutingTransportEnvelope", "FieldPhaseRoutingTransportEnvelopeCase",
    "run_field_phase_routing_transport_envelope",
    "field_phase_routing_transport_envelope_report",
    "FIELD_OPERATIONAL_PHASE_ROUTING_TRANSPORT_ENVELOPE_SCHEMA",
    "FieldOperationalPhaseRoutingTransportEnvelope",
    "FieldOperationalPhaseRoutingTransportEnvelopeCase",
    "run_field_operational_phase_routing_transport_envelope",
    "field_operational_phase_routing_transport_envelope_report",
    "FIELD_SCREENING_REPORT_SCHEMA", "FIELD_SENSOR_SUPERPOSITION_REPORT_SCHEMA",
    "FIELD_DROPLET_HANDOFF_REFINEMENT_REPORT_SCHEMA",
    "FIELD_JOINT_MEASURED_HISTORY_ENVELOPE_REPORT_SCHEMA",
    "FIELD_MEASURED_HISTORY_ENVELOPE_REPORT_SCHEMA",
    "FIELD_SEMI_FV_ENVELOPE_REPORT_SCHEMA",
    "FIELD_SENSOR_ARRAY_UNCERTAINTY_ENVELOPE_REPORT_SCHEMA",
    "field_screening_report", "field_sensor_superposition_report",
    "field_droplet_handoff_refinement_report",
    "field_joint_measured_history_envelope_report",
    "field_measured_history_envelope_report",
    "field_semi_fv_envelope_report",
    "field_sensor_array_uncertainty_envelope_report",
    "write_field_screening_report", "field_refinement_report",
    "write_field_refinement_report",
    "FIELD_BATCH_MANIFEST_SCHEMA", "FIELD_BATCH_SUMMARY_SCHEMA",
    "FieldBatchCase", "FieldBatchExport",
    "field_batch_decision_summary",
    "export_field_screening_batch",
    "FIELD_BATCH_INPUT_SCHEMA", "FieldBatchExecutionOptions", "FieldBatchInputCase",
    "FieldBatchInput", "field_batch_input_from_mapping", "read_field_batch_input_json",
    "FIELD_SCREENING_INPUT_SCHEMA", "FIELD_PHASE_ROUTING_SCREENING_INPUT_SCHEMA",
    "FieldConditionalReviewAuthorization", "FieldPhaseRoutingTransportInput",
    "FieldScreeningCase",
    "field_screening_case_from_mapping", "field_screening_request_from_mapping",
    "read_field_screening_case_json", "read_field_screening_request_json",
    "FIELD_OPERATIONAL_GATE_CODES", "FIELD_OPERATIONAL_SCREENING_DECISION_SCHEMA",
    "FieldOperationalScreeningDecision",
    "evaluate_field_operational_screening", "field_operational_screening_decision_record",
    "FIELD_OPERATIONAL_UNCERTAINTY_ENVELOPE_SCHEMA",
    "FieldOperationalUncertaintyEnvelope", "FieldOperationalUncertaintyEnvelopeCase",
    "run_field_operational_uncertainty_envelope",
    "field_operational_uncertainty_envelope_report",
    "FIELD_OPERATIONAL_MEASURED_HISTORY_ENVELOPE_SCHEMA",
    "FieldOperationalMeasuredHistoryEnvelope",
    "FieldOperationalMeasuredHistoryEnvelopeCase",
    "run_field_operational_joint_measured_history_envelope",
    "run_field_operational_joint_pressure_driven_history_envelope",
    "field_operational_joint_measured_history_envelope_report",
    "FIELD_OPERATIONAL_SENSOR_ARRAY_ENVELOPE_SCHEMA",
    "FieldOperationalSensorArrayEnvelope",
    "FieldOperationalSensorArrayEnvelopeCase",
    "run_field_operational_sensor_array_envelope",
    "field_operational_sensor_array_envelope_report",
    "FIELD_OPERATIONAL_SOURCE_SENSOR_ENVELOPE_SCHEMA",
    "FieldOperationalSourceSensorEnvelope",
    "FieldOperationalSourceSensorEnvelopeCase",
    "run_field_operational_source_sensor_envelope",
    "field_operational_source_sensor_envelope_report",
    "MeasuredTimeSeries", "MeasuredReleaseHistory", "PressureDrivenMeasuredHistory", "FieldMeasuredFlashSchedule",
    "MeasuredHistoryQualityCriteria", "MeasuredHistoryQualityAssessment",
    "assess_measured_history_quality",
    "FieldMeasuredFlashEnvelopeCase", "FieldMeasuredFlashEnvelope",
    "FieldMeasuredHistoryScreeningCase", "FieldMeasuredHistoryScreeningEnvelope",
    "FieldJointMeasuredHistoryScreeningCase", "FieldJointMeasuredHistoryScreeningEnvelope",
    "direct_vapour_schedule_from_measured_history",
    "direct_vapour_schedule_envelope_from_measured_history",
    "direct_vapour_schedule_from_pressure_driven_history",
    "direct_vapour_schedule_envelope_from_pressure_driven_history",
    "request_with_measured_flash_schedule",
    "request_with_pressure_driven_history_schedule",
    "run_field_joint_measured_history_envelope",
    "run_field_joint_pressure_driven_history_envelope",
    "run_field_measured_history_envelope",
    "run_field_pressure_driven_history_envelope",
    "HistorianCsvChannel", "MeasuredHistoryCsvMap", "PressureDrivenHistoryCsvMap", "MeasuredHistoryCsvProvenance",
    "ImportedMeasuredReleaseHistory", "ImportedPressureDrivenMeasuredHistory", "read_measured_history_csv",
    "read_pressure_driven_history_csv",
    "direct_vapour_schedule_from_imported_history",
    "direct_vapour_schedule_from_imported_pressure_driven_history",
    "PoolVapourLaunchBoundary", "FieldPoolVapourSchedule",
    "pool_vapour_schedule_from_phase_routing", "request_with_pool_vapour_schedule",
    "distributed_source_from_pool_vapour_schedule",
]
